import { Company, Lead } from "@/types";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Acme AI",
    url: "https://acme-ai.com",
    logo_url: null,
    description:
      "AI-powered workflow automation for small businesses. Just raised Series A to expand their product team.",
    industry: "AI / Machine Learning",
    stage: "series_a",
    funding_amount: 4000000,
    funded_date: "2026-03-20",
    team_size: 8,
    designer_count: 0,
    engineer_count: 4,
    source: "crunchbase",
    source_url: "https://crunchbase.com/acme-ai",
    score: "hot",
    signals: ["just_funded", "no_designer", "hiring_engineers"],
    created_at: "2026-03-25T10:00:00Z",
    updated_at: "2026-03-25T10:00:00Z",
  },
  {
    id: "2",
    name: "BuildKit",
    url: "https://buildkit.dev",
    logo_url: null,
    description:
      "Developer tools for rapid prototyping. YC W26 batch company founded by two ex-Google engineers.",
    industry: "Developer Tools",
    stage: "seed",
    funding_amount: 500000,
    funded_date: "2026-03-01",
    team_size: 3,
    designer_count: 0,
    engineer_count: 2,
    source: "yc",
    source_url: "https://ycombinator.com/companies/buildkit",
    score: "hot",
    signals: ["accelerator_batch", "no_designer", "technical_founders"],
    created_at: "2026-03-24T10:00:00Z",
    updated_at: "2026-03-24T10:00:00Z",
  },
  {
    id: "3",
    name: "Flowstate",
    url: "https://flowstate.app",
    logo_url: null,
    description:
      "Productivity app for creative professionals. Solo technical founder, just launched beta on Product Hunt.",
    industry: "Productivity",
    stage: "pre_seed",
    funding_amount: null,
    funded_date: null,
    team_size: 1,
    designer_count: 0,
    engineer_count: 1,
    source: "producthunt",
    source_url: "https://producthunt.com/posts/flowstate",
    score: "warm",
    signals: ["new_launch", "no_designer", "technical_founders"],
    created_at: "2026-03-27T10:00:00Z",
    updated_at: "2026-03-27T10:00:00Z",
  },
  {
    id: "4",
    name: "NexaPay",
    url: "https://nexapay.io",
    logo_url: null,
    description:
      "Fintech startup building payment infrastructure for emerging markets. Hiring their first product designer.",
    industry: "Fintech",
    stage: "series_a",
    funding_amount: 8000000,
    funded_date: "2026-02-15",
    team_size: 22,
    designer_count: 0,
    engineer_count: 12,
    source: "crunchbase",
    source_url: "https://crunchbase.com/nexapay",
    score: "hot",
    signals: ["just_funded", "hiring_first_designer", "no_designer"],
    created_at: "2026-03-22T10:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "5",
    name: "GreenGrid",
    url: "https://greengrid.energy",
    logo_url: null,
    description:
      "Climate tech startup optimizing energy grid distribution using machine learning.",
    industry: "Climate Tech",
    stage: "seed",
    funding_amount: 2000000,
    funded_date: "2026-03-10",
    team_size: 6,
    designer_count: 0,
    engineer_count: 4,
    source: "crunchbase",
    source_url: "https://crunchbase.com/greengrid",
    score: "warm",
    signals: ["just_funded", "no_designer"],
    created_at: "2026-03-23T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
  },
  {
    id: "6",
    name: "LoopDesk",
    url: "https://loopdesk.com",
    logo_url: null,
    description:
      "Async collaboration tool for remote teams. Launched on Product Hunt last week, getting traction.",
    industry: "SaaS / Collaboration",
    stage: "pre_seed",
    funding_amount: null,
    funded_date: null,
    team_size: 2,
    designer_count: 0,
    engineer_count: 2,
    source: "producthunt",
    source_url: "https://producthunt.com/posts/loopdesk",
    score: "warm",
    signals: ["new_launch", "technical_founders", "no_designer"],
    created_at: "2026-03-26T10:00:00Z",
    updated_at: "2026-03-26T10:00:00Z",
  },
  {
    id: "7",
    name: "Medivault",
    url: "https://medivault.health",
    logo_url: null,
    description:
      "Health tech platform for secure patient data management. Series B with growing engineering team but no design lead.",
    industry: "Health Tech",
    stage: "series_b",
    funding_amount: 25000000,
    funded_date: "2026-01-20",
    team_size: 45,
    designer_count: 1,
    engineer_count: 20,
    source: "crunchbase",
    source_url: "https://crunchbase.com/medivault",
    score: "cool",
    signals: ["just_funded", "hiring_engineers"],
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "8",
    name: "Stackpilot",
    url: "https://stackpilot.dev",
    logo_url: null,
    description:
      "AI code review tool for engineering teams. YC W26 batch, technical co-founders from Stripe.",
    industry: "Developer Tools",
    stage: "seed",
    funding_amount: 500000,
    funded_date: "2026-03-01",
    team_size: 4,
    designer_count: 0,
    engineer_count: 3,
    source: "yc",
    source_url: "https://ycombinator.com/companies/stackpilot",
    score: "hot",
    signals: ["accelerator_batch", "no_designer", "technical_founders"],
    created_at: "2026-03-25T10:00:00Z",
    updated_at: "2026-03-25T10:00:00Z",
  },
];

export const mockLeads: Lead[] = mockCompanies.map((company) => ({
  id: `lead-${company.id}`,
  company_id: company.id,
  status: "new" as const,
  notes: null,
  outreach_angle: null,
  updated_at: company.created_at,
  company,
}));
