import { JobListing, Lead } from "@/types";

const today = new Date();
function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const mockJobs: JobListing[] = [
  {
    id: "1",
    title: "Freelance Product Designer — Mobile App Redesign",
    company_name: "Acme AI",
    company_url: "https://acme-ai.com",
    description:
      "Looking for a freelance product designer to lead the redesign of our mobile app. 3-month engagement, experience with AI products preferred.",
    location: "Remote",
    job_type: "freelance",
    source: "linkedin",
    source_url: "https://linkedin.com/jobs/view/123456",
    posted_date: daysAgo(1),
    score: "hot",
    tags: ["freelance", "product designer", "mobile", "AI", "remote"],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "2",
    title: "Contract Product Designer for B2B SaaS Platform",
    company_name: "BuildKit",
    company_url: "https://buildkit.dev",
    description:
      "We need a contract product designer to help us build our v2 design system and redesign core workflows. 6-month contract with possible extension.",
    location: "Remote (US)",
    job_type: "contract",
    source: "linkedin",
    source_url: "https://linkedin.com/jobs/view/234567",
    posted_date: daysAgo(2),
    score: "hot",
    tags: ["contract", "product designer", "B2B", "SaaS", "design system"],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "3",
    title: "Freelance UX/UI Designer — Fintech Startup",
    company_name: "NexaPay",
    company_url: "https://nexapay.io",
    description:
      "Early-stage fintech startup looking for a freelance UX/UI designer to design our payment dashboard from scratch. Equity + pay.",
    location: "San Francisco / Remote",
    job_type: "freelance",
    source: "linkedin",
    source_url: "https://linkedin.com/jobs/view/345678",
    posted_date: daysAgo(3),
    score: "hot",
    tags: ["freelance", "UX/UI", "fintech", "startup", "equity"],
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: "4",
    title: "Freelance Product Designer — Health Tech",
    company_name: "Medivault",
    company_url: "https://medivault.health",
    description:
      "Contract product designer needed to help redesign our patient portal. Must have health tech or regulated industry experience.",
    location: "Remote",
    job_type: "freelance",
    source: "linkedin",
    source_url: "https://linkedin.com/jobs/view/456789",
    posted_date: daysAgo(4),
    score: "warm",
    tags: ["freelance", "product designer", "health tech", "patient portal"],
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
  },
  {
    id: "5",
    title: "Part-Time Product Designer for Developer Tools Startup",
    company_name: "Stackpilot",
    company_url: "https://stackpilot.dev",
    description:
      "YC-backed startup looking for a part-time product designer (20hrs/week) to own our product design. Technical background a plus.",
    location: "Remote",
    job_type: "part_time",
    source: "linkedin",
    source_url: "https://linkedin.com/jobs/view/567890",
    posted_date: daysAgo(1),
    score: "hot",
    tags: ["part-time", "product designer", "developer tools", "YC"],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "6",
    title: "Freelance Product Designer — E-commerce Redesign",
    company_name: "ShopFlow",
    company_url: "https://shopflow.co",
    description:
      "Need an experienced freelance product designer to redesign our checkout flow and product pages. 2-month project.",
    location: "New York / Remote",
    job_type: "freelance",
    source: "indeed",
    source_url: "https://indeed.com/viewjob?jk=abc123",
    posted_date: daysAgo(2),
    score: "warm",
    tags: ["freelance", "product designer", "e-commerce", "checkout"],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "7",
    title: "Contract Senior Product Designer",
    company_name: "GreenGrid Energy",
    company_url: "https://greengrid.energy",
    description:
      "Climate tech company seeking a contract senior product designer for our energy management dashboard. 4-month engagement.",
    location: "Remote (US/EU)",
    job_type: "contract",
    source: "dribbble",
    source_url: "https://dribbble.com/jobs/greengrid-senior-pd",
    posted_date: daysAgo(5),
    score: "warm",
    tags: ["contract", "senior", "product designer", "climate tech", "dashboard"],
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: "8",
    title: "Freelance Product Designer — AI Writing Tool",
    company_name: "Proseify",
    company_url: "https://proseify.com",
    description:
      "Solo founder looking for a freelance product designer to design the v1 of our AI writing assistant. Strong portfolio required.",
    location: "Remote",
    job_type: "freelance",
    source: "wellfound",
    source_url: "https://wellfound.com/l/proseify-product-designer",
    posted_date: daysAgo(0),
    score: "hot",
    tags: ["freelance", "product designer", "AI", "writing", "v1"],
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
];

export const mockLeads: Lead[] = mockJobs.map((job) => ({
  id: `lead-${job.id}`,
  job_id: job.id,
  status: "new" as const,
  notes: null,
  updated_at: job.created_at,
  job,
}));
